/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package placarvolei;

import java.util.Timer;
import java.util.TimerTask;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Rodrigo
 */
public class Tela extends javax.swing.JFrame {

    /**
     * Creates new form Tela
     */
    public Tela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Pontos1 = new javax.swing.JLabel();
        Pontos2 = new javax.swing.JLabel();
        setTime2 = new javax.swing.JLabel();
        setTime1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        labelVencedor = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setToolTipText("");
        jPanel1.setMinimumSize(new java.awt.Dimension(10, 10));

        jLabel4.setText("Home");

        jLabel5.setText("Visitor");

        Pontos1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        Pontos1.setText("00");

        Pontos2.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        Pontos2.setText("00");

        setTime2.setText("0");

        setTime1.setText("0");

        jButton1.setText("Iniciar Partida");

        jButton2.setText("Ponto Time 2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Ponto Time 1");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel1.setText("Placar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(184, 184, 184))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(setTime1)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2)
                                .addGap(4, 4, 4))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Pontos1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(17, 17, 17)))
                                .addGap(55, 55, 55)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(15, 15, 15))
                                    .addComponent(Pontos2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)))
                        .addComponent(setTime2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(jButton1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(labelVencedor, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1)
                .addGap(69, 69, 69)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Pontos1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Pontos2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(setTime2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(setTime1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelVencedor, javax.swing.GroupLayout.DEFAULT_SIZE, 15, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        int pontos = Integer.parseInt(Pontos1.getText());
        pontos++;
        Pontos1.setText(
            "" + pontos);
        verificarplacarTime1();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int pontos = Integer.parseInt(Pontos2.getText());
        pontos++;
        Pontos2.setText(
            "" + pontos);
        verificarplacarTime2();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Pontos1;
    private javax.swing.JLabel Pontos2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelVencedor;
    private javax.swing.JLabel setTime1;
    private javax.swing.JLabel setTime2;
    // End of variables declaration//GEN-END:variables

    private void verificarplacarTime1() {
        int pontos1 = Integer.parseInt(Pontos1.getText());
        int pontos2 = Integer.parseInt(Pontos2.getText());

        if (setTime1.getText().equals("2") && setTime2.getText().equals("2")) {
            if (pontos1 == 15) {
                if (pontos2 < 14) {
                    int set1 = Integer.parseInt(setTime1.getText());
                    set1++;
                    setTime1.setText("" + set1);
                    Pontos1.setText("0");
                    Pontos2.setText("0");
                    if (set1 == 3) {
                        JOptionPane.showMessageDialog(null, "Home is the winner");
                        dispose();
                    }
                }
            } else if (pontos1 >= 15) {
                if ((pontos1 - pontos2) == 2 || pontos1 == 20) {
                    int set1 = Integer.parseInt(setTime1.getText());
                    set1++;
                    setTime1.setText("" + set1);
                    Pontos1.setText("0");
                    Pontos2.setText("0");
                    if (set1 == 3) {
                        JOptionPane.showMessageDialog(null, "Home is the winner");
                        dispose();
                    }
                }
            }
        } else {
            if (pontos1 == 25) {
                if (pontos2 < 24) {
                    int set1 = Integer.parseInt(setTime1.getText());
                    set1++;
                    setTime1.setText("" + set1);
                    Pontos1.setText("0");
                    Pontos2.setText("0");
                    if (set1 == 3) {
                        JOptionPane.showMessageDialog(null, "Home is the winner");
                        dispose();
                    }
                }
            } else if (pontos1 >= 25) {
                if ((pontos1 - pontos2) == 2 || pontos1 == 30) {
                    int set1 = Integer.parseInt(setTime1.getText());
                    set1++;
                    setTime1.setText("" + set1);
                    Pontos1.setText("0");
                    Pontos2.setText("0");
                    if (set1 == 3) {
                        JOptionPane.showMessageDialog(null, "Home is the winner");
                        dispose();
                    }
                }
            }
        }
    }

    private void verificarplacarTime2() {
        int pontos1 = Integer.parseInt(Pontos1.getText());
        int pontos2 = Integer.parseInt(Pontos2.getText());
        if (setTime1.getText().equals("2") && setTime2.getText().equals("2")) {
            if (pontos2 == 15) {
                if (pontos1 < 14) {
                    int set2 = Integer.parseInt(setTime2.getText());
                    set2++;
                    setTime2.setText("" + set2);
                    Pontos1.setText("0");
                    Pontos2.setText("0");
                    if (set2 == 3) {
                        JOptionPane.showMessageDialog(null, "Visitor is the winner");
                        dispose();
                    }
                }
            } else if (pontos2 >= 15) {
                if ((pontos2 - pontos1) == 2 || pontos2 == 20) {
                    int set2 = Integer.parseInt(setTime2.getText());
                    set2++;
                    setTime2.setText("" + set2);
                    Pontos1.setText("0");
                    Pontos2.setText("0");
                    if (set2 == 3) {
                        JOptionPane.showMessageDialog(null, "Visitor is the winner");
                        dispose();
                    }
                }
            }
        } else {
            if (pontos2 == 25) {
                if (pontos1 < 24) {
                    int set2 = Integer.parseInt(setTime2.getText());
                    set2++;
                    setTime2.setText("" + set2);
                    Pontos1.setText("0");
                    Pontos2.setText("0");
                    if (set2 == 3) {
                        JOptionPane.showMessageDialog(null, "Visitor is the winner");
                        dispose();
                    }
                }
            } else if (pontos2 >= 25) {
                if ((pontos2 - pontos1) == 2 || pontos2 == 30) {
                    int set2 = Integer.parseInt(setTime2.getText());
                    set2++;
                    setTime2.setText("" + set2);
                    Pontos1.setText("0");
                    Pontos2.setText("0");
                    if (set2 == 3) {
                        JOptionPane.showMessageDialog(null, "Visitor is the winner");
                        dispose();
                    }
                }
            }
        }
    }
}
